# For documentation on this fine, see https://doc.rust-lang.org/cargo/reference/manifest.html

[package]
name = "prodctrl"
version = "0.1.0"
authors = [ "Patrick Miller" ]
edition = "2021"
description = "Production control automation"
license = "MIT OR Apache-2.0"
repository = "https://github.com/paddymills/highsteel-prodctrl"
default-run = "pc"

[features]
default = []
full = [ "db", "gui", "xl" ]
db = [ "async", "mssql" ]
gui = []
xl = [ "simple_excel_writer" ]

async = [ "async_once", "async-trait", "tokio", "tokio-util" ]
mssql = [ "bb8", "bb8-tiberius", "tiberius" ]

[dependencies]
chrono = "0.4"
csv = "1.1"
figment = { version = "0.10", features = ["env", "toml"] }
glob = "0.3"
lazy_static = "1.4"
rayon = "1.5"
regex = "1.5"
serde = { version = "1.0", features = ["derive"] }

# logging
log = "0.4"
simplelog = "0.12"

# cli/tui
# TODO: simplify progress (linya, nutmeg, pbr)
clap = { version = "3.2", features = ["derive"] }
clap-verbosity-flag = "1.0.1"
linya = "0.3"
nutmeg = "0.1"
pbr = "1.0"
requestty = "0.4"

# Excel
simple_excel_writer = { version = "0.2.0", optional = true }

# MSSQL database
bb8 = { version = "0.8", optional = true }
# see tokio-util dependency note below before upgrading bb8-tiberius version
bb8-tiberius = { version = "0.12.0", optional = true }
tiberius = { version = "0.10", features = [ "sql-browser-tokio", "integrated-auth-gssapi" ], optional = true }

# async
# TODO: remove async_once (only needed in examples)
async_once = { version = "0.2", optional = true }
async-trait = { version = "0.1", optional = true }
crossbeam = { version = "0.8", optional = true }

[dependencies.tokio]
version = "1.19"
features = ["net", "rt-multi-thread", "sync"]
optional = true

[dependencies.tokio-util]
# tokio-util version must match version used in bb8-tiberius for type compatibility
version = "0.6.2"
features = [ "compat" ]
optional = true

[dev-dependencies]
figment = { version = "0.10", features = ["env", "test", "toml"] }

[[bin]]
name = "sap_confirmation_files"
required-features = [ "db" ]

[[bin]]
name = "pc"
path = "src\\bin\\cli.rs"
required-features = [ "db" ]

[[example]]
name = "compare"
required-features = ["db"]

[[example]]
name = "lb"
required-features = ["db"]
