[package]
name = "prodctrl"
version = "0.1.0"
authors = ["Patrick Miller"]
edition = "2021"
description = "what runs production control"
license = "MIT OR Apache-2.0"
repository = "https://github.com/paddymills/highsteel-prodctrl"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
default = ["api"]
api = []
async = [ "async_once", "async-trait", "tokio", "tokio-util" ]
db = [ "async", "bb8", "bb8-tiberius", "tiberius" ]
xl = []
full = [ "api", "db", "xl" ]

[dependencies]
lazy_static = "1.4"
serde = { version = "1.0", features = ["derive"] }

# logging
log = "0.4"
simplelog = "0.12"

# needs split into features
chrono = "0.4"
csv = "1.1"
figment = { version = "0.10", features = ["env", "toml"] }
glob = "0.3"
uncased = "0.9"
rayon = "1.5"
regex = "1.5"
simple_excel_writer = "0.2.0"
clap = { version = "3.2", features = ["derive"] }
linya = "0.3"
nutmeg = "0.1"
pbr = "1.0"
requestty = "0.4"

# MSSQL database
bb8 = { version = "0.8", optional = true }
bb8-tiberius = { version = "0.12", optional = true }
tiberius = { version = "0.10", features = [ "sql-browser-tokio", "integrated-auth-gssapi" ], optional = true }

# async
async_once = { version = "0.2", optional = true }
async-trait = { version = "0.1", optional = true }
# tokio = { version = "1.19", features = ["net", "rt-multi-thread", "sync"], optional = true }
tokio = { version = "1.19", features = ["full"], optional = true }
tokio-util = { version = "0.7", features = ["compat"], optional = true }
crossbeam = { version = "0.8", optional = true }

[dev-dependencies]
figment = { version = "0.10", features = ["env", "test", "toml"] }

[[example]]
name = "compare"
required-features = ["db"]

[[example]]
name = "sap_cnf_files"

[[example]]
name = "bom"
required-features = ["db"]

[[example]]
name = "lb"
required-features = ["db"]
