[package]
name = "prodctrl-config"
version = "0.1.0"
edition = "2021"

[dependencies]
rust-embed = { version = "6.4.1", features = ["debug-embed", "include-exclude"] }
serde = { version = "1.0.144", features = ["derive"] }
toml = "0.5.9"
