[package]
name = "prodctrl-bin"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# cli/tui
clap = { version = "4.0", features = ["derive"] }
clap-verbosity-flag = "2.0"

# logging
log = "0.4"
simplelog = "0.12"
