[package]
name = "sap-confirmation-files"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
csv = "1.1"
lazy_static = "1.4"
rayon = "1.5"
regex = "1.5"
serde = { version = "1.0", features = ["derive"] }

# cli/tui
# TODO: simplify progress (linya, nutmeg, pbr)
clap = { version = "3.2", features = ["derive"] }
clap-verbosity-flag = "1.0.1"
linya = "0.3"

# logging
log = "0.4"
simplelog = "0.12"
